version: '3.8'

services:
  # ClickHouse数据库
  clickhouse:
    image: clickhouse/clickhouse-server:23.8-alpine
    container_name: sysarmor-clickhouse
    hostname: clickhouse
    ports:
      - "8123:8123"  # HTTP接口
      - "9000:9000"  # Native接口
      - "9009:9009"  # HTTP接口（备用）
    environment:
      CLICKHOUSE_DB: sysarmor_events
      CLICKHOUSE_USER: sysarmor
      CLICKHOUSE_PASSWORD: sysarmor123
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
      - ./config/clickhouse-config.xml:/etc/clickhouse-server/config.xml:ro
      - ./config/users.xml:/etc/clickhouse-server/users.xml:ro
      - ./init:/docker-entrypoint-initdb.d:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  # ClickHouse数据卷
  clickhouse_data:
    driver: local
  clickhouse_logs:
    driver: local

# 使用默认网络，适合独立部署
