version: '3.8'

services:
  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: sysarmor-postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sysarmor_meta
      POSTGRES_USER: sysarmor
      POSTGRES_PASSWORD: sysarmor123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      TZ: Asia/Shanghai
      PGTZ: Asia/Shanghai
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf:ro
      - ./init:/docker-entrypoint-initdb.d:ro
    command: >
      postgres 
      -c config_file=/etc/postgresql/postgresql.conf
      -c log_destination=stderr
      -c logging_collector=on
      -c log_directory=/var/log/postgresql
      -c log_filename=postgresql-%Y-%m-%d_%H%M%S.log
      -c log_rotation_age=1d
      -c log_rotation_size=100MB
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sysarmor -d sysarmor_meta"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
volumes:
  # PostgreSQL数据卷
  postgres_data:
    driver: local
  postgres_logs:
    driver: local

# 使用默认网络，适合独立部署
