# Elasticsearch配置文件
# SysArmor EDR/XDR平台专用配置

# 发现配置
discovery.type: single-node

# 路径配置
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# 内存配置
bootstrap.memory_lock: false

# 安全配置
xpack.security.enabled: false
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# 监控配置
xpack.monitoring.collection.enabled: true

# 索引配置
action.auto_create_index: true
action.destructive_requires_name: true

# 性能配置
indices.memory.index_buffer_size: 10%
indices.memory.min_index_buffer_size: 48mb

# 日志配置
logger.level: INFO
