# Elasticsearch配置文件
# SysArmor EDR/XDR平台专用配置
# 配置参数通过环境变量统一管理

# 集群配置
cluster.name: ${ELASTICSEARCH_CLUSTER_NAME}
node.name: ${ELASTICSEARCH_NODE_NAME}

# 网络配置
network.host: ${ELASTICSEARCH_NETWORK_HOST}
http.port: ${ELASTICSEARCH_HTTP_PORT}
transport.port: ${ELASTICSEARCH_TRANSPORT_PORT}

# 发现配置
discovery.type: single-node

# 路径配置
path.data: ${ELASTICSEARCH_DATA_PATH}
path.logs: ${ELASTICSEARCH_LOGS_PATH}

# 内存配置
bootstrap.memory_lock: false

# 安全配置
xpack.security.enabled: ${XPACK_SECURITY_ENABLED}
xpack.security.enrollment.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# 监控配置
xpack.monitoring.collection.enabled: true

# 索引配置
action.auto_create_index: true
action.destructive_requires_name: true

# 性能配置
indices.memory.index_buffer_size: 10%
indices.memory.min_index_buffer_size: 48mb

# 日志配置
logger.level: INFO
