# Kibana配置文件
# SysArmor EDR/XDR平台专用配置

# 服务器配置
server.name: sysarmor-kibana

# 监控配置
monitoring.ui.container.elasticsearch.enabled: true

# 日志配置
logging:
  appenders:
    default:
      type: console
      layout:
        type: json
  root:
    level: info

# 数据配置
path.data: /usr/share/kibana/data

# UI配置
server.rewriteBasePath: false

# 性能配置
elasticsearch.pingTimeout: 1500
elasticsearch.requestHeadersWhitelist: ["authorization"]
