version: '3.8'

services:
  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: sysarmor-redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  # Redis数据卷
  redis_data:
    driver: local

# 使用默认网络，适合独立部署
